apiVersion: v2
name: flask-app
description: A Helm chart for Flask Authentication Application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - flask
  - authentication
  - python
  - web-application
home: https://github.com/company/flask-devops-project
sources:
  - https://github.com/company/flask-devops-project
maintainers:
  - name: DevOps Team
    email: devops-team@company.com
